# Generated by Django 4.2.8 on 2024-05-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_likes_alter_post_author_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(verbose_name='Entradilla'),
        ),
    ]
