# Generated by Django 4.2.8 on 2024-05-21 15:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=core.models.profile_picture_path, verbose_name='Imagen'),
        ),
    ]
