# Generated by Django 4.2.8 on 2024-06-18 22:32

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_post_likes_alter_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='content',
            field=models.TextField(blank=True, max_length=1350, null=True, verbose_name='Contenido'),
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=core.models.profile_picture_path, verbose_name='Imagen'),
        ),
    ]
