# Generated by Django 4.2.8 on 2024-06-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='about/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_picture_path', verbose_name='Imagen'),
        ),
    ]
