# Generated by Django 4.2.8 on 2024-06-20 19:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_about_image_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=core.models.profile_picture_path, verbose_name='Imagen'),
        ),
    ]
